version: "3.7"
services:
  app:
    command: "yarn start"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL
        - WRI_API_URL
        - PORT
        - NODE_ENV
        - GOOGLE_ANALYTICS
    image: aq-flood-front
    env_file: .env
    ports:
      - "7000:7000"
    restart: always
    container_name: aq-flood
